### ISSUE TITLE
install_generator.rb orders plugins incorrectly, causing postcss-next @apply deprecation warning

### ISSUE THREAD

**Issue by mitchwd** [IcaliaLabs/tailwindcss-rails#2]
The install generator puts the tailwindcss plugin AFTER the postcss-cssnext plugin, which causes the following deprecation warning on tailwind css compile:

```
You are using @apply rule and custom property sets.
This feature won't be included in the next major release of postcss-cssnext.
This most likely won't get any more support from browser vendors as the spec is yet considered deprecated and alternative solutions are being discussed.
Read more about the reason here https://github.com/pascalduez/postcss-apply.
```
By reordering the plugins, the deprecation warning is not shown.

```
plugins:
  postcss-import: {}
  tailwindcss: './app/javascript/css/tailwind.js'
  postcss-cssnext: {}
```

See tailwindcss/tailwindcss/issues/381 for more information.

Thanks,
Mitch
